### ISSUE TITLE
Please guide us how to install?

### ISSUE THREAD

**Issue by bdjunayed** [pedzed/laravel-susy-bower#1]

**Comment by pedzed** [comment]
This was for Laravel 5.3. Laravel 5.4 already comes with Vue. I'll consider updating the code with instructions.

**Comment by pedzed** [comment]
I'm fine by upgrading to Laravel 5.4, but I'm not sure if I should wait for Susy 3 or not.

>Susy 3 is fundamentally different from Susy 1 & 2, so you'll run into a lot of issues like this if you are updating an old project. Susy 3 doesn't have any mixins, so it also doesn't have settings related to output. In your code, that means `gutter-position`, `with-layout`, `container`, and `susy-clearfix` are all gone.

It's in Alpha 5 now.

**Comment by bdjunayed** [comment]
whatever, Susy is a nice tool for grid layout, I am learning this.
